version: 2
registries:
  npm-devops:
    type: npm-registry
    url: https://pkgs.dev.azure.com/Appnetwise/anw_application/_packaging/Cloud-Carbon-Footprint/npm/registry/
    username: Appnetwise
    password: ${{ secrets.NPM_TOKEN }}
updates:
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - npm-devops
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    target-branch: "dependabot-fixes"
    labels:
      - dependencies