nodeLinker: node-modules

npmAlwaysAuth: true
npmAuthIdent: "c2FpdmFtc2k6M3g1a2h6bDV6Z3JyYXk0cHJkb3ZsZTVqdTJianF5d2RudmR2cGt0ZXlnaHpvaWpvMmhnYQ=="
npmPublishRegistry: "https://pkgs.dev.azure.com/Appnetwise/anw_application/_packaging/Cloud-Carbon-Footprint/npm/registry/"
npmRegistryServer: "https://pkgs.dev.azure.com/Appnetwise/anw_application/_packaging/Cloud-Carbon-Footprint/npm/registry/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://github.com/mskelton/yarn-plugin-outdated/raw/main/bundles/@yarnpkg/plugin-outdated.js"

yarnPath: .yarn/releases/yarn-3.3.0.cjs
