nodeLinker: node-modules

npmAlwaysAuth: true
npmAuthIdent: "%NPM_AUTH_TOKEN%"
npmPublishRegistry: "https://pkgs.dev.azure.com/Appnetwise/anw_application/_packaging/Cloud-Carbon-Footprint/npm/registry/"
npmRegistryServer: "https://pkgs.dev.azure.com/Appnetwise/anw_application/_packaging/Cloud-Carbon-Footprint/npm/registry/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://github.com/mskelton/yarn-plugin-outdated/raw/main/bundles/@yarnpkg/plugin-outdated.js"

yarnPath: .yarn/releases/yarn-3.3.0.cjs
