apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloud-carbon-footprint.fullname" . }}-client
  labels:
    {{ include "cloud-carbon-footprint.labels" . | nindent 4 }}
    app.kubernetes.io/component: client
data:
{{ (tpl (.Files.Glob "config/nginx.conf").AsConfig .) | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloud-carbon-footprint.fullname" . }}-client-config
  labels:
    {{ include "cloud-carbon-footprint.labels" . | nindent 4 }}
    app.kubernetes.io/component: client
data:
  {{- range $key, $val := .Values.client.configmap.config }}
  {{ $key }}: {{ tpl $val $ | quote }}
  {{- end}}