name: CD

on:
  workflow_dispatch:
    inputs:
      acr_version:
        description: 'ACR tag tool version'
        required: true
        default: 'latest'
        type: string
      REGISTRY_URL:
        description: 'Docker Registry URL'
        required: true
        default: 'anwapplication.azurecr.io'
        type: choice
        options:
          - anwapplication.azurecr.io
      RELEASE:
        description: 'Release Version'
        required: true
        default: latest
        type: string

  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [dev]

jobs:
  Deployment:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: true
      matrix:
        target: [ dev, qa, prod ]
    uses: ./.github/workflows/deployment.yml
    with:
      target-env: ${{ matrix.target }}
      REGISTRY_URL: ${{ inputs.REGISTRY_URL }}
      RELEASE: ${{ inputs.RELEASE }}
      ACR_VERSION: ${{ inputs.acr_version }}
      run-id: ${{ github.event.workflow_run.id }}
    secrets: inherit
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
