name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches:
      - 'dev'

jobs:

  deployment:

    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: Legit-Labs/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: ci.yml
        workflow_conclusion: success
        branch: dev
        check_artifacts:  false
    - name: Load Docker Images
      run: |
        cd artifacts
        for targz in $(find . -type f -name "*.tar.gz")
        do
          gunzip $targz
          docker load -q -i ${targz:0:-3}
        done
        docker push cloudcarbonfootprint/client:latest
        docker push cloudcarbonfootprint/api:latest
