name: PR
on:
  pull_request:
    branches: [main, trunk]
    types: [opened, synchronize, reopened]
    paths-ignore:
        - 'microsite/**'
jobs:
  lint-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ignore draft pull requests
        if: github.event.pull_request.draft
        run: exit
      - uses: ./.github/build
        with:
          node-version: ${{ matrix.node-version }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: lint
        run: yarn lint
      - name: test and upload coverage
        run: yarn test

   